env:
  node: true
  es2021: true
  jest: true
  vitest: true
extends:
  - airbnb-base
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - '@stylistic'
  - import
rules:
  no-console: 0
  import/extensions:
    - error
    - ignorePackages
    - js: always
  no-underscore-dangle: 0
  class-methods-use-this: 0
  max-classes-per-file: 0
  import/prefer-default-export: 0
  '@stylistic/semi': ['error', 'never']
  '@stylistic/quotes': ['error', 'single']
  '@stylistic/comma-dangle': ['error', 'always-multiline']
  '@stylistic/arrow-parens': ['error', 'always']
  '@stylistic/brace-style': ['error', '1tbs']
  '@stylistic/no-trailing-spaces': 'error'